### ISSUE TITLE
how to use type 42  in  a PostScript file?

### ISSUE THREAD

**Issue by xiaoping88** [scriptituk/ttf2pscid2#1]
I am a newer for Postscript, i want to output Chinese text to printer in PostScript.  I use your tools to convert TTF to ps , like this 
gswin64.exe -q -o- -dNODISPLAY -sttf=c:\windows\fonts\msyh.ttf -ssubset='中文abc123chinese' -st42=msyh2.ps ttf2pscid2.ps

I tried to write PostScript code in end of the msys2.ps file , 

/MicrosoftYaHei findfont 20 scalefont setfont
150 325 moveto
(中文abc123chinese) show

then use GSview to show the msys2.ps , content is messy code.
could help me  to give me a example ? thanks!

**Comment by scriptituk** [comment]
Sorry for the delay, I have only just seen your comment!

Create the Type42 font file like this:

`gswin64.exe -q -o- -dNODISPLAY -sttf=c:\windows\fonts\msyh.ttf -ssubset='中文abc123chinese' -st42=msyh2.t42 ttf2pscid2.ps`

then create this PostScript file msyh2.ps:
```
%!PS-Adobe-3.0

(msyh2.t42) run % font file
(string.ps) run % UTF8 support

/MicrosoftYaHei findfont 20 scalefont setfont
150 325 moveto
(中文abc123chinese) utf8toutf16be show
showpage
```
The text needs to be in UTF16 (BMP) or UCS-2, that's why it looked messy. The `utf8toutf16be` command in `string.ps` in [pslutils](https://github.com/scriptituk/pslutils). will convert from UTF8.

GSview will not work because it uses the -dSAFER switch which throws /invalidfileaccess for the run command, so you need to embed `msyh2.t42` and `string.ps` inside `msyh2.ps`. But GSview converts to PDF so you can use GhostScript directly like this:
`gs -q -sDEVICE=pdfwrite -o msyh2.pdf msyh2.ps`
then use GSview on `msyh2.pdf` instead.
