### ISSUE TITLE
What could be the problem ?

### ISSUE THREAD

**Issue by Toxa58rus** [scriptituk/ttf2pscid2#3]
![1567584172595455216380569577108](https://user-images.githubusercontent.com/54885223/64236682-9ac58c00-cf03-11e9-9409-383d01f9f088.jpg)

I also wanted to know what is meant by the word directory(this is cmap?) in the example that was given, cidfont dup / sfnts %DIRECTORY <....>
And I would like to know what the array is for, the line above.  Why are there two values ​​everywhere, and there are three, plus the third position is negative [100 6 -2].
And another question is how the Cyrillic alphabet is encoded, otherwise I have squares instead of Cyrillic.

**Comment by scriptituk** [comment]
The error was caused by GhostScript v.9.26 renaming the operator shellarguments to .shellarguments; I have updated `ttf2pscid2.ps` to fix it.

The word 'directory' in the first sfnts comment means the TTF table directory.

The nested arrays passed to operator `cidmap1` or `cidmap2` contain 2 or more values; negative values indicate CID range and length efficiently, e.g. `…[160 3 98 -12 16 110 -706]…` for Arial. The `heredoc` code for `cidmap1/2` in `ttf2pscid2.ps` shows the uncompressed implementation.

All alphabets are encoded as Basic Multilingual Plane Unicode. Cyrillic works fine.
